"use client";
import { useEffect, useState } from 'react';
import { content, skillGroups } from './resumeData';
import { certificates } from './certificates';
import DownloadButton from './DownloadButton';

const work = [
  {name:'Sikarin Hospital',tag:'HEALTHCARE',stack:'Angular / .NET', th:'พัฒนาโมดูลจัดการข้อมูลผู้ป่วยในระบบ HIS ให้รองรับขั้นตอนการทำงานของโรงพยาบาล',en:'Developed patient-data management modules for hospital information workflows.'},
  {name:'IRPC',tag:'BUSINESS INTELLIGENCE',stack:'Tableau / SQL',th:'ออกแบบรายงานและ Dashboard เพื่อให้ผู้บริหารใช้ข้อมูลประกอบการตัดสินใจ',en:'Built reports and dashboards to support executive decision-making.'},
  {name:'TQM & Viriyah',tag:'INSURANCE',stack:'Angular / Frontend',th:'พัฒนา Frontend สำหรับขั้นตอนการทำประกันภัยรถยนต์',en:'Built frontend interfaces for motor-insurance workflows.'},
  {name:'PUMPUI',tag:'RETAIL',stack:'Web Application / POS',th:'พัฒนาระบบจัดการการขายและสต็อกสินค้าให้เชื่อมต่อกับการทำงานของร้านค้า',en:'Developed sales and inventory management for retail operations.'},
];
export default function ResumeClient() {
  const [lang,setLang]=useState('th');
  const [type,setType]=useState('resume');
  const [preview,setPreview]=useState(false);
  const c=content[lang]; const th=lang==='th'; const t=(a,b)=>th?a:b;
  useEffect(()=>{document.documentElement.lang=lang;},[lang]);
  return <div className="site">
    <a className="skip-link" href="#main">{t('ข้ามไปเนื้อหา','Skip to content')}</a>
    <header className="navigation"><a className="brand" href="#main"><span className="monogram">S.</span> SATJA<span className="brand-dot"> / DEV</span></a>
      <nav aria-label={t('เมนูหลัก','Main navigation')}><a href="#work">{t('ผลงาน','Work')}</a><a href="#experience">{t('ประสบการณ์','Experience')}</a><a href="#credentials">{t('ใบรับรอง','Credentials')}</a></nav>
      <div className="nav-end"><div className="language" aria-label="Language">{['th','en'].map(l=><button key={l} aria-pressed={lang===l} onClick={()=>setLang(l)}>{l.toUpperCase()}</button>)}</div><a className="nav-download" href="#documents">CV / Resume ↗</a></div>
    </header>
    <main id="main">
      <section className="hero wrap">
        <div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> FULL STACK DEVELOPER · THAILAND</p><h1>{t('เริ่มที่ปัญหา','Start with the problem.')}<br/><span>{t('สร้างสิ่งที่ใช้ได้จริง','Build what works.')}</span></h1>
          <p className="intro-name">{t('สัจจา ชัยแสนพา','Satja Chaiseanpha')} <span> / Fluke</span></p>
          <p className="hero-description">{t('ผมชอบทำความเข้าใจปัญหาที่ซับซ้อน แล้วเปลี่ยนให้เป็นระบบที่ใช้งานได้จริง ตั้งแต่เว็บแอปพลิเคชันและ API ไปจนถึงข้อมูลที่ช่วยให้คนตัดสินใจได้ดีขึ้น','I enjoy understanding complex problems and turning them into practical systems. From web applications and APIs to data that helps people make better decisions.')}</p>
          <div className="actions"><a href="#work" className="button primary">{t('สำรวจผลงาน','Explore my work')} ↗</a><a href="#documents" className="button secondary">CV / Resume ↓</a></div>
          <div className="hero-facts"><div><strong>4+</strong><span>{t('ปีในงานพัฒนาซอฟต์แวร์','years in software development')}</span></div><div><strong>Full stack</strong><span>.NET · Angular · React</span></div><div><strong>Problem solver</strong><span>{t('เข้าใจโจทย์ ก่อนเขียนโค้ด','Understand first. Then build.')}</span></div></div>
        </div>
        <div className="portrait-area"><div className="portrait-label">THE PERSON BEHIND THE CODE</div><div className="portrait-frame"><img src="/profile-satja.png" alt={t('สัจจา ชัยแสนพา','Satja Chaiseanpha')} width="620" height="720" fetchPriority="high"/></div><div className="portrait-caption"><span>01 / SATJA CHAISEANPHA</span><span>NONG BUA LAMPHU, TH</span></div><div className="portrait-note"><span aria-hidden="true">↳</span><p>{t('เข้าใจปัญหา ออกแบบทางออก','Understand. Design. Deliver.')}<br/><strong>{t('แล้วลงมือทำให้เกิดขึ้นจริง','Make it work in the real world.')}</strong></p></div></div>
      </section>
      <div className="stack-strip"><div className="wrap"><span>MY EVERYDAY TOOLKIT</span><strong>.NET / C#</strong><strong>Angular</strong><strong>React & Next.js</strong><strong>SQL</strong><strong>Tableau</strong></div></div>
      <section className="section wrap" id="approach"><div className="section-heading"><p className="eyebrow">01 / MINDSET</p><h2>{t('คนแก้ปัญหา ที่เขียนโค้ดได้','A problem solver who codes.')}</h2><p>{t('เทคโนโลยีเป็นเครื่องมือ จุดเริ่มต้นของผมคือคนที่ต้องใช้ระบบและปัญหาที่เขาต้องเจอ','Technology is a tool. I start with the people using a system and the problems they face.')}</p></div><div className="approach-grid">{[
        [t('เข้าใจโจทย์','Understand the problem'),t('แปลงความต้องการทางธุรกิจให้เป็นขอบเขตงานที่ชัดเจน มองทั้งผู้ใช้ ข้อมูล และข้อจำกัด','Translate business needs into a clear scope, considering users, data and constraints.')],
        [t('เลือกทางออกที่เหมาะ','Choose a practical solution'),t('เชื่อม Frontend, API และฐานข้อมูลเข้าด้วยกัน เลือกเครื่องมือให้เหมาะกับงานและการดูแลต่อ','Connect frontend, APIs and databases with tools suited to the task and future maintenance.')],
        [t('รับผิดชอบจนส่งมอบ','Own the delivery'),t('ดูแลงานตั้งแต่การออกแบบไปจนถึงส่งมอบ ใช้ AI ช่วยทำงานโดยตรวจความถูกต้องของ Logic','Take work from design through delivery, using AI while checking the correctness of the logic.')],
      ].map(([title,desc],i)=><article key={title}><span className="step">0{i+1} <span>↗</span></span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
      <section className="work-section" id="work"><div className="wrap section"><div className="section-heading split"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>{t('จากโจทย์ธุรกิจ สู่ระบบจริง','Real problems. Working systems.')}</h2></div><p>{t('ตัวอย่างงานที่มีส่วนพัฒนาระหว่างทำงานที่ Multita','Selected contributions during my time at Multita.')}</p></div><div className="work-grid">{work.map((w,i)=><article className="work-card" key={w.name}><div className="work-top"><span>{w.tag}</span><span>0{i+1}</span></div><h3>{w.name}</h3><p>{w[lang]}</p><div className="work-stack">{w.stack}</div></article>)}</div><div className="live-work"><span>{t('ทดลองดูเว็บที่ทำ','Explore live websites')}</span><a href="https://pf-exam-final.vercel.app" target="_blank" rel="noreferrer">Exam / Next.js ↗</a><a href="https://pf-smart-serve.vercel.app/" target="_blank" rel="noreferrer">Smart Serve / POS ↗</a><a href="https://github.com/aminadmin16" target="_blank" rel="noreferrer">GitHub ↗</a></div></div></section>
      <section className="section wrap experience-section" id="experience"><div className="section-heading"><p className="eyebrow">03 / EXPERIENCE</p><h2>{t('ประสบการณ์ที่ต่อยอดกัน','Experience that connects.')}</h2><p>{t('จากระบบองค์กร สู่งานอิสระ และการแก้ปัญหาหน้างาน','Enterprise software, independent delivery and hands-on technical work.')}</p></div><div className="timeline">{c.experiences.map(e=><article key={e.title}><p className="date">{e.date}</p><h3>{e.title}</h3><p className="meta">{e.meta}</p><ul>{e.bullets.map(b=><li key={b}>{b}</li>)}</ul></article>)}</div></section>
      <section className="section wrap skills-section" id="skills"><div className="section-heading"><p className="eyebrow">04 / CAPABILITIES</p><h2>{t('เครื่องมือที่ใช้สร้างทางออก','My tools for the job.')}</h2></div><div className="skills-grid">{skillGroups.map(g=><div key={g.key}><h3>{g.title[lang]}</h3><div className="tags">{g.skills.map(s=><span key={s}>{s}</span>)}</div></div>)}</div></section>
      <section className="section wrap" id="credentials"><div className="section-heading"><p className="eyebrow">05 / EDUCATION & CREDENTIALS</p><h2>{t('พื้นฐาน และหลักฐานการลงมือทำ','Foundations. And evidence.')}</h2></div><div className="credentials-grid"><article className="education"><span className="eyebrow">{c.education.date}</span><h3>{c.education.school}</h3><p>{c.education.degree}</p><strong>{c.education.gpa}</strong><p>{c.education.note}</p></article><article className="certificate-card"><a href={certificates[0].file} target="_blank" rel="noreferrer" aria-label={t('เปิดภาพเกียรติบัตร','Open certificate image')}><img src={certificates[0].file} alt={t('เกียรติบัตร NSC 2020 โครงการสมาร์ทเอลเดอร์ ของสัจจา ชัยแสนพา','NSC 2020 Smart Elder certificate awarded to Satja Chaiseanpha')} loading="lazy" width="1920" height="1384"/></a><div><span className="eyebrow">NSTDA · NSC 2020</span><h3>{t('โครงการสมาร์ทเอลเดอร์','Smart Elder project')}</h3><p>{t('ผู้พัฒนาโครงการที่ได้รับทุนสนับสนุน ในหมวดโปรแกรมเพื่อช่วยคนพิการและผู้สูงอายุ ระดับนิสิต นักศึกษา','Developer of a funded project in the student category for software supporting people with disabilities and older adults.')}</p><p className="meta">6 {t('มีนาคม 2563','March 2020')}</p><a className="text-link" href={certificates[0].source} target="_blank" rel="noreferrer">{t('ดูต้นฉบับเกียรติบัตร','View original certificate')} ↗</a></div></article></div></section>
      <section className="documents-section" id="documents"><div className="wrap document-grid"><div><p className="eyebrow">06 / TAKE IT WITH YOU</p><h2>{t('รู้จักผมให้มากขึ้น','Get the full picture.')}</h2><p>{t('เลือกเอกสารให้เหมาะกับสิ่งที่คุณต้องการอ่าน พร้อมใบประกาศแนบต่อท้ายในไฟล์เดียว','Choose the level of detail you need. The certificate is included at the end of every PDF.')}</p><span className="attachment-note">✓ {t('แนบเกียรติบัตร NSC 2020 แล้ว','NSC 2020 certificate included')}</span></div><div className="document-picker"><div className="document-tabs" role="group" aria-label={t('รูปแบบเอกสาร','Document format')}>{['resume','cv'].map(v=><button aria-pressed={type===v} key={v} onClick={()=>{setType(v);setPreview(false);}}>{v==='cv'?'CV':'Resume'}</button>)}</div><span className="eyebrow">{type==='resume'?'THE HIGHLIGHTS':'THE COMPLETE STORY'}</span><h3>{type==='resume'?t('กระชับ ตรงประเด็น','Concise and focused'):t('ประสบการณ์ฉบับเต็ม','Experience in detail')}</h3><p>{type==='resume'?t('ประวัติย่อ 1 หน้า เน้นทักษะ ประสบการณ์สำคัญ และผลงาน เหมาะกับการสมัครงาน','A one-page overview of key skills, experience and work. Ready for job applications.'):t('ประวัติฉบับละเอียด รวมหน้าที่ โครงการ ทักษะ และการศึกษา เหมาะสำหรับทำความรู้จักเชิงลึก','A detailed record of responsibilities, projects, skills and education.')}</p><p className="document-meta">{lang.toUpperCase()} · PDF · {t('พร้อมใบรับรอง 1 หน้า','Includes 1 certificate page')}</p><div className="actions"><DownloadButton lang={lang} type={type}/><button className="button secondary" onClick={()=>setPreview(!preview)} aria-expanded={preview}>{preview?t('ปิดตัวอย่าง','Close preview'):t('ดูตัวอย่าง','Preview')} ↗</button></div></div></div>{preview&&<div className="wrap pdf-preview"><object key={`${type}-${lang}`} data={`/documents/Satja-Chaiseanpha-${type}-${lang}.pdf`} type="application/pdf" aria-label={`${type} ${lang}`}><p>{t('เบราว์เซอร์นี้ไม่รองรับการดู PDF ในหน้าเว็บ','This browser cannot display an embedded PDF.')} <a href={`/documents/Satja-Chaiseanpha-${type}-${lang}.pdf`} target="_blank" rel="noreferrer">{t('เปิด PDF','Open PDF')}</a></p></object></div>}</section>
      <section className="contact-section wrap" id="contact"><p className="eyebrow">LET’S SOLVE SOMETHING</p><h2>{t('มีโจทย์ที่อยากชวนคุย?','Have a problem in mind?')}</h2><a className="contact-email" href="mailto:knownaddress90@gmail.com">knownaddress90@gmail.com ↗</a><div className="contact-links"><a href="tel:0835014158">083-501-4158</a><a href="https://github.com/aminadmin16" target="_blank" rel="noreferrer">GitHub ↗</a><span>{t('หนองบัวลำภู · ประเทศไทย','Nong Bua Lamphu · Thailand')}</span></div></section>
    </main><footer className="wrap"><span>© {new Date().getFullYear()} Satja Chaiseanpha</span><span>THOUGHTFULLY BUILT. PURPOSEFULLY SOLVED.</span><a href="#main">{t('กลับด้านบน','Back to top')} ↑</a></footer>
  </div>;
}
