import {readFile} from 'node:fs/promises';
import {content,skillGroups,profileHighlights,TECH_KEYWORDS} from '../app/resumeData.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function highlight(text){const words=[...TECH_KEYWORDS].sort((a,b)=>b.length-a.length).map(w=>w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));return text.split(new RegExp(`(${words.join('|')})`,'g')).map(p=>TECH_KEYWORDS.includes(p)?`<b class="text-highlight">${esc(p)}</b>`:esc(p)).join('');}
const bullets=items=>`<ul class="dot-list">${items.map(x=>`<li>${highlight(x)}</li>`).join('')}</ul>`;
export async function classicResume(lang,fontCSS){
 const c=content[lang];const css=await readFile(new URL('./resume-classic.css',import.meta.url),'utf8');
 const photo=(await readFile(new URL('../public/profile-satja-studio.png',import.meta.url))).toString('base64');
 const title=s=>`<h2 class="block-title">${esc(s)}</h2>`;
 const contacts=[['T','tel:0835014158','083-501-4158'],['@','mailto:knownaddress90@gmail.com','knownaddress90@gmail.com'],['GH','https://github.com/aminadmin16','github.com/aminadmin16'],['TH',null,lang==='th'?'หนองบัวลำภู · ประเทศไทย':'Nong Bua Lamphu · Thailand']];
 const sites=[['Online Resume','https://resume-satja.vercel.app','resume-satja.vercel.app'],['Exam (Next.js)','https://pf-exam-final.vercel.app','pf-exam-final.vercel.app'],['Smart Serve (POS)','https://pf-smart-serve.vercel.app','pf-smart-serve.vercel.app']];
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><style>${fontCSS}\n${css}\n@page{size:A4;margin:0}body{font-family:Noto,sans-serif;background:white}.paper{box-shadow:none;border-radius:3mm}.contact-icon{font:700 5pt Noto}.profile-card{padding:4mm}.person-name{font-size:15pt}.right-panel{padding:3.4mm}.exp-head{gap:1.5mm}.exp-pill{padding:1mm 2.5mm;font-size:7.8pt}.exp-date{font-size:7.8pt}.paper-grid{height:auto}.dot-list{text-align:left!important}.photo{object-fit:cover;object-position:center 20%}</style></head><body><div class="paper"><div class="paper-grid"><div class="col-left"><div class="profile-card"><div class="photo-frame"><img class="photo" src="data:image/png;base64,${photo}" alt="Satja Chaiseanpha"></div><h1 class="person-name">${lang==='th'?'สัจจา<br>ชัยแสนพา':'SATJA<br>CHAISEANPHA'}</h1>${title(c.sections.contact)}<ul class="contact-list">${contacts.map(([label,url,text])=>`<li><span class="contact-icon">${label}</span><span class="contact-text">${url?`<a href="${url}">${esc(text)}</a>`:esc(text)}</span></li>`).join('')}</ul>${title(c.sections.skills)}<div class="skill-list">${skillGroups.map(g=>`<div class="skill-group"><p class="skill-group-name">${esc(g.title[lang])}</p><ul class="skill-run">${g.skills.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div>`).join('')}</div>${title(c.sections.portfolio)}<dl class="pair-table">${sites.map(([name,url,text])=>`<div class="pair-row"><dt>${name}</dt><dd><a href="${url}">${text}</a></dd></div>`).join('')}</dl>${title(c.sections.education)}<div class="edu-block"><p class="edu-school">${esc(c.education.school)}</p><p class="edu-degree">${esc(c.education.degree)}</p><p class="edu-gpa">${esc(c.education.gpa)}</p><time class="edu-date">${esc(c.education.date)}</time><p class="edu-note">${esc(c.education.note)}</p></div></div><div class="outer-block">${title(c.sections.highlights)}<ul class="skill-run skill-run--center">${profileHighlights.map(h=>`<li>${esc(h)}</li>`).join('')}</ul></div></div><div class="col-right"><div class="right-panel"><section class="about-card"><span class="tag-pill">${esc(c.eyebrow)}</span><p class="about-text">${highlight(c.profileSummary.trim())}</p></section>${title(c.sections.experience)}<div class="exp-list">${c.experiences.map(e=>`<article class="exp"><div class="exp-head"><span class="exp-pill">${esc(e.title)}</span><time class="exp-date">${esc(e.date)}</time></div><p class="exp-meta">${esc(e.meta)}</p>${e.intro?`<p class="exp-label">${esc(e.intro)}</p>`:''}${bullets(e.bullets)}${e.projects?`<p class="exp-label">${esc(e.projectsTitle)}</p>${bullets(e.projects)}`:''}</article>`).join('')}</div></div></div></div></div></body></html>`;
}
