import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium} from 'playwright';
import {PDFDocument} from 'pdf-lib';
import {content,skillGroups} from '../app/resumeData.js';
import {certificates} from '../app/certificates.js';
import {classicResume} from './classic-resume.mjs';
const root=process.cwd();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const font=async file=>(await readFile(path.join(root,'public/fonts',file))).toString('base64');
const thai=await font('noto-sans-thai.woff2'),latin=await font('noto-sans-latin.woff2');
const fontCSS=`@font-face{font-family:Noto;font-weight:100 900;src:url(data:font/woff2;base64,${thai}) format('woff2');unicode-range:U+2D7,U+303,U+331,U+E01-E5B,U+200C-200D,U+25CC}@font-face{font-family:Noto;font-weight:100 900;src:url(data:font/woff2;base64,${latin}) format('woff2');unicode-range:U+0000-00FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+304,U+308,U+329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}`;
const css=`${fontCSS} @page{size:A4;margin:14mm 16mm}*{box-sizing:border-box}body{margin:0;font-family:Noto,sans-serif;color:#172a37;font-size:9.5pt;line-height:1.55}h1{font-size:27pt;line-height:1.25;margin:0 0 3mm;letter-spacing:-.6pt}h2{font-size:11pt;color:#1756df;border-bottom:1px solid #dce3e7;padding-bottom:1.3mm;margin:5mm 0 2.3mm;letter-spacing:.3pt;break-after:avoid}h3{font-size:10pt;margin:0 0 1mm;break-after:avoid}p{margin:0 0 2mm}header{border-bottom:2pt solid #1756df;padding-bottom:4mm;margin-bottom:4mm}.role{font-size:12pt;color:#1756df;font-weight:600}.contact{font-size:8.5pt;color:#526470;margin-top:2mm}a{color:inherit;text-decoration:none}.meta{font-size:8pt;color:#526470}.date{font-size:8.5pt;color:#1756df;margin-bottom:1mm}ul{padding-left:4mm;margin:1mm 0 0}li+li{margin-top:1mm}.job{break-inside:avoid;margin-bottom:4mm}.skills{font-size:9pt}.skills p{margin-bottom:1.5mm}.compact{font-size:8.5pt;line-height:1.4}.compact h1{font-size:25pt}.compact h2{margin-top:2.3mm;margin-bottom:1.5mm;font-size:10pt}.compact .job{margin-bottom:2.4mm}.compact li+li{margin-top:.7mm}.compact h3{font-size:9pt}.compact .date{font-size:8pt}.compact .meta{font-size:7.5pt}.compact header{margin-bottom:3mm;padding-bottom:3mm}.compact .skills{font-size:8.5pt}.cv-break{break-before:page}.footer-note{font-size:8pt;color:#526470;border-top:1px solid #dce3e7;padding-top:3mm;margin-top:4mm}.skills-row{break-inside:avoid}.certificate-title{font-weight:700}`;
const summary={th:'Full Stack Developer ประสบการณ์ 4+ ปี พัฒนาเว็บแอปพลิเคชันด้วย .NET, Angular, React และ Next.js รวมถึง RESTful API และ Tableau Dashboard ชอบวิเคราะห์ปัญหา แปลงความต้องการทางธุรกิจเป็นระบบที่ใช้งานได้จริง และรับผิดชอบงานตั้งแต่ออกแบบจนส่งมอบ',en:'Full Stack Developer with 4+ years of experience building web applications with .NET, Angular, React and Next.js, alongside RESTful APIs and Tableau dashboards. Enjoys analysing problems, translating business needs into practical systems and owning delivery from design to handover.'};
const brief={
th:[['พัฒนาเว็บด้วย Angular / React / Next.js และออกแบบ RESTful API ด้วย .NET / Node.js','วิเคราะห์ความต้องการ ออกแบบระบบ และส่งมอบโครงการให้ลูกค้า'],['สำรวจพื้นที่และเสนอทางเลือกงบประมาณ ติดตั้งระบบเครือข่ายและ CCTV ครบวงจร'],['พัฒนาเว็บองค์กรด้วย Angular + .NET และ Dashboard ด้วย Tableau','ร่วมพัฒนาระบบ HIS (ศิครินทร์), BI (IRPC), ประกันภัย (TQM / วิริยะ) และแอป Android (PUMPUI) ด้วย Java / Android Studio'],['พัฒนา Frontend ด้วย Angular และ Backend ด้วย Java / Spring Boot']],
en:[['Built web applications with Angular / React / Next.js and RESTful APIs with .NET / Node.js.','Translated requirements into technical designs and delivered client projects.'],['Surveyed sites, proposed budget options and installed network and CCTV systems.'],['Developed enterprise applications with Angular + .NET and Tableau dashboards.','Contributed to HIS (Sikarin), BI (IRPC), insurance (TQM / Viriyah) and the PUMPUI Android app using Java / Android Studio.'],['Developed Angular interfaces and Java / Spring Boot backend modules.']]};
function header(lang,type){return `<header><h1>${lang==='th'?'สัจจา ชัยแสนพา':'SATJA CHAISEANPHA'}</h1><div class="role">Full Stack Developer / Problem Solver</div><div class="contact"><a href="mailto:knownaddress90@gmail.com">knownaddress90@gmail.com</a> · <a href="tel:0835014158">083-501-4158</a><br><a href="https://github.com/aminadmin16">github.com/aminadmin16</a> · ${lang==='th'?'หนองบัวลำภู ประเทศไทย':'Nong Bua Lamphu, Thailand'} · ${type.toUpperCase()}</div></header>`;}
function job(e,bullets,projects){return `<article class="job"><div class="date">${esc(e.date)}</div><h3>${esc(e.title)}</h3><p class="meta">${esc(e.meta)}</p><ul>${bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>${projects&&e.projects?`<p style="margin-top:2mm"><b>${esc(e.projectsTitle)}</b></p><ul>${e.projects.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>`:''}</article>`;}
function education(c){return `<h2>${esc(c.sections.education)}</h2><h3>${esc(c.education.school)}</h3><p>${esc(c.education.degree)} · ${esc(c.education.date)} · ${esc(c.education.gpa)}</p>`;}
function creds(lang){return `<h2>${lang==='th'?'เกียรติบัตรและโครงการ':'CREDENTIALS & PROJECTS'}</h2><p class="certificate-title">NSC 2020 - ${lang==='th'?'โครงการสมาร์ทเอลเดอร์':'Smart Elder project'}</p><p>${lang==='th'?'ผู้พัฒนาโครงการที่ได้รับทุนสนับสนุน หมวดโปรแกรมเพื่อช่วยคนพิการและผู้สูงอายุ ระดับนิสิต นักศึกษา โดย สวทช. วันที่ 6 มีนาคม 2563':'Developer of a funded student project in software for people with disabilities and older adults. NSTDA, 6 March 2020.'}</p>`;}
function html(lang,type){
 const c=content[lang];
 const skills=skillGroups.slice(0,4).map(g=>`<p class="skills-row"><b>${esc(g.title[lang])}:</b> ${esc(g.skills.join(' · '))}</p>`).join('');
 const jobs=c.experiences.map((e,i)=>job(e,brief[lang][i],false));
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><style>${css}</style></head><body class="compact">${header(lang,type)}<h2>${esc(c.sections.summary)}</h2><p>${esc(summary[lang])}</p><h2>${esc(c.sections.skills)}</h2><div class="skills">${skills}</div><h2>${esc(c.sections.experience)}</h2>${jobs.join('')}${education(c)}${creds(lang)}<p class="footer-note">${lang==='th'?'ใบประกาศต้นฉบับแนบในหน้าถัดไป':'Original certificate attached on the following page(s).'}</p></body></html>`;
}
await mkdir(path.join(root,'public/documents'),{recursive:true});await mkdir(path.join(root,'tmp/pdfs'),{recursive:true});
const browser=await chromium.launch({headless:true});
try{for(const lang of ['th','en'])for(const type of ['resume','cv']){
 const page=await browser.newPage();await page.setContent(type==='resume'?await classicResume(lang,fontCSS):html(lang,type),{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);
 if(type==='resume'){
  await page.evaluate(async()=>{await Promise.all([...document.images].map(img=>img.decode()));});
  const overflow=await page.evaluate(()=>{const paper=document.querySelector('.paper').getBoundingClientRect();return [...document.querySelectorAll('.paper-grid p,.paper-grid li,.paper-grid h1,.paper-grid h2,.exp-head')].some(el=>{const r=el.getBoundingClientRect();return r.bottom>paper.bottom-10||r.right>paper.right-10;});});
  if(overflow)throw new Error(`Classic Resume ${lang} content overflows the page`);
 }
 const bytes=await page.pdf({format:'A4',printBackground:true,preferCSSPageSize:true});const doc=await PDFDocument.load(bytes);
 await writeFile(path.join(root,'tmp/pdfs',`${type}-${lang}-body.pdf`),bytes);const expected=1;if(doc.getPageCount()!==expected)throw new Error(`${type}-${lang}: expected ${expected} body pages, got ${doc.getPageCount()}`);
 for(const cert of certificates){const assetPath=path.resolve(root,'public',cert.file.replace(/^\//,''));const allowed=path.resolve(root,'public/certificates')+path.sep;if(!assetPath.startsWith(allowed))throw new Error('Certificate must be inside public/certificates');const asset=await readFile(assetPath);
 if(asset.subarray(0,5).toString()==='%PDF-'){const original=await PDFDocument.load(asset);for(const copied of await doc.copyPages(original,original.getPageIndices()))doc.addPage(copied);}else{let img;if(asset[0]===0xff&&asset[1]===0xd8)img=await doc.embedJpg(asset);else if(asset.subarray(1,4).toString()==='PNG')img=await doc.embedPng(asset);else throw new Error('Unsupported certificate file');const landscape=img.width>img.height;const [w,h]=landscape?[841.89,595.28]:[595.28,841.89];const p=doc.addPage([w,h]);const s=Math.min((w-40)/img.width,(h-40)/img.height);p.drawImage(img,{x:(w-img.width*s)/2,y:(h-img.height*s)/2,width:img.width*s,height:img.height*s});}}
 doc.setTitle(`Satja Chaiseanpha - ${type.toUpperCase()} (${lang.toUpperCase()})`);doc.setAuthor('Satja Chaiseanpha');doc.setSubject('Professional experience and original certificates');const name=`Satja-Chaiseanpha-${type}-${lang}.pdf`;await writeFile(path.join(root,'public/documents',name),await doc.save());console.log(`${name}: ${expected} body + ${doc.getPageCount()-expected} certificate pages`);await page.close();
}}finally{await browser.close();}
